default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  username: jientdongoc
  password: ''

development:
  <<: *default
  database: model_final_development

test:
  <<: *default
  database: model_final_test

production:
  <<: *default
  database: model_final_production
  username: model_final
  password: <%= ENV['MODEL_FINAL_DATABASE_PASSWORD'] %>
